# Generated by Django 5.0.4 on 2024-05-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('goal', models.IntegerField()),
                ('raised', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='causes/')),
            ],
        ),
    ]
