# Generated by Django 5.0.4 on 2024-05-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_charityactivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharityActivity',
        ),
    ]
