# Generated by Django 5.0.4 on 2024-05-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_delete_charityactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('goal', models.PositiveIntegerField()),
                ('raised', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='causes/')),
            ],
        ),
    ]
