# Generated by Django 5.0.4 on 2024-05-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_cause_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause_title', models.CharField(max_length=255)),
                ('cause_description', models.TextField()),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='donation_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Cause',
        ),
    ]
