# Generated by Django 5.0.4 on 2024-05-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_donationcause_delete_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcause',
            name='image',
            field=models.ImageField(blank=True, upload_to='donationimages/'),
        ),
    ]
