# Generated by Django 5.0.4 on 2024-05-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_blogpost_alter_donationcause_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('purpose', models.CharField(choices=[('general', 'General Inquiry'), ('event_join', 'Join Event')], max_length=20)),
                ('event_name', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
